version: '2'
services:
  vsenti_database:
    image: mysql:5.7
    container_name: vsenti_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: vsenti
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: vsenti_database
